branches:
  only:
  - testing
  except:
  - master

dist: focal
#dist: bionic

# setting lbg/ubg works fine with bionic + MATLAB R2020a, not with focal + MATLAB R2021a (latest, default)

# this is only required to install MATLAB such that we
# have access to HSL on the machine
language: python

addons:
    apt_packages:
        - gfortran
git:
    submodules: false

before_install: 
    - openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv -in github_deploy_key.enc -out github_deploy_key -d
    - chmod 600 github_deploy_key
    - eval $(ssh-agent -s)
    - ssh-add github_deploy_key
    - git submodule update --init
    - sudo apt-get -y install python3-pip
    - sudo apt-get -y install python3-setuptools
     
    # ONLY FOR FOCAL
    - sudo apt-get install libgfortran5
    - sudo apt-get install liblapack-dev
    - sudo apt-get install libblas-dev

    - pushd external/coin_hsl_source && ./configure && make && popd

    # ONLY FOR BIONIC
    # - sudo apt-get install libgfortran3 

install:
    - python3 -m pip install -e .
    - export LD_LIBRARY_PATH=$(pwd)/external/qpOASES/bin:$LD_LIBRARY_PATH
    - export LD_LIBRARY_PATH=$(pwd)/external/casadi/installation/lib:$LD_LIBRARY_PATH
    - export LD_LIBRARY_PATH=$(pwd)/external/coin_hsl_source/.libs/:$LD_LIBRARY_PATH
    - pushd test
    # - matlab -batch "fileID = fopen('matlab_root_path.txt','w'); fprintf(fileID,'%s', matlabroot); fclose(fileID);"
    - python3 install_dependencies.py

    # - export LD_LIBRARY_PATH=$(<matlab_root_path.txt)/bin/glnxa64:$LD_LIBRARY_PATH
    - export LD_LIBRARY_PATH=$(pwd)/fsqp_solver:$LD_LIBRARY_PATH
    - echo $LD_LIBRARY_PATH
    - pwd
    - ls

script:
    - python3 test.py
